### ISSUE TITLE
add content reports to pipeline

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-pipeline#28]
It would be useful to add a target to the makefile which runs various SPARQL queries to create reports helping us identify any connectivity issues, etc. Examples:

- are there OWL individuals in models that don't have a Biolink type? Or have only biolink:NamedThing as a Biolink type?
- are there edges (OWL object property assertions) in models that don't have a Biolink type?

**Comment by rajshruti18** [comment]
Added a SPARQL query. Created pull request- https://github.com/NCATS-Tangerine/cam-pipeline/pull/29.

**Comment by balhoff** [comment]
We have some initial reports running.
