### ISSUE TITLE
create workflow step to assert any Uniprot identifier is subclass of protein

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-pipeline#31]
We can use a SPARQL construct to query the loaded models for Uniprot ids and just inject a subclass of relation to [protein](http://purl.obolibrary.org/obo/CHEBI_36080). This is a workaround for https://github.com/geneontology/noctua/issues/693.

**Comment by balhoff** [comment]
Next step here is to add a target to the makefile, similar to https://github.com/NCATS-Tangerine/cam-pipeline/blob/9fe96bf0cfd4d9795501ff2f672f378adb4cb154/Makefile#L31-L32

and then merge the turtle file into ontologies-merged.ttl.

**Comment by rajshruti18** [comment]
> Next step here is to add a target to the makefile, similar to
> 
> https://github.com/NCATS-Tangerine/cam-pipeline/blob/9fe96bf0cfd4d9795501ff2f672f378adb4cb154/Makefile#L31-L32
> 
> and then merge the turtle file into ontologies-merged.ttl.

@balhoff Done! https://github.com/NCATS-Tangerine/cam-pipeline/pull/33

**Comment by balhoff** [comment]
Great, thank you.
